### ISSUE TITLE
Hi there mean

### ISSUE THREAD

**Issue by seungwook0417** [dryrain39/dryrain39#1]
영어 인사말 중에서도 가장 간단한 말이 Hi, there. 혹은 Hello, there.입니다. 여기서 there은 왜 쓰는지 알고 계십니까?
우리말로는 '거기' 이니까 "거기 안녕하세요?" 라고 하는 뜻인가요?
 
there는 미국인들 사이에서 '아무개 씨'로 통합니다. 그러니까 사람을 소개받는 자리에서 상대방 이름을 아직 모를 때, 혹은 모르는 사람을 소개받은 자리에서 상대방 이름을 아직 모를 때, 혹은 모르는 사람에게 정식으로 말을 붙일 때에 쓰는 말이지요.
 
상대방 이름은 모르겠는데 적당히 존대는 해줘야겠고, 그럴 때 there를 붙입니다. 올바른 해석은 "안녕하세요?"라고 말을 건넬 때 씁니다.

**Comment by dryrain39** [comment]
아… 네…
